# If not running interactively, don't do anything
[[ $- != *i* ]] && return

alias ls='ls --color=auto'
export PS1="\[\e[01;32m\][\u\[\e[0m\]\[\e[00;37m\] \[\e[0m\]\[\e[01;33m\]\W\[\e[0m\]\[\e[01;32m\]]\[\e[0m\]\[\e[00;37m\] \[\e[0m\]\[\e[01;31m\]>>\[\e[0m\]\[\e[00;37m\] \[\e[0m\]"
export EDITOR="nano"
